services:
  - type: web
    name: rag-service
    runtime: python
    plan: free

    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn rag.rag_main:app --host 0.0.0.0 --port $PORT"

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
